#page title
page_title                                : CalBot                                    # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234567890                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://cgsphoto.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : https://kiwicrushers.github.io/calbot/assets/appicon.png                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : CalBot                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free
app_description                           : Nutrition for you.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : KiwiCrushers                                
your_link                                 : https://kiwicrushers.com                     
your_city                                 : Tallahassee                                
email_address                             : somekiwi@gmail.com
facebook_username                         : kiwiface                                          
instagram_username                        : kiwig
twitter_username                          : kiwitweets
github_username                           : kiwicrushers
youtube_username                          : kiwisvlogs



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Calorie Calculator
    description                           : Designed to record your daily calorie intake. Find out more information at www.kiwicrushers.com/calbot
    fontawesome_icon_name                 : magic
    
  - title                                 : Supported for iOS and Andriod
    description                           : Works great for both Iphone and Android phones.
    fontawesome_icon_name                 : mobile

  - title                                 : Video Support
    description                           : Check out our how-to videos and learn more about CalBot.
    fontawesome_icon_name                 : play-circle

  - title                                 : Settings Made for You
    description                           : Reset your calorie intake every day, week, month, or customise it yourself.
    fontawesome_icon_name                 : sync

  - title                                 : Easy to Tweak
    description                           : Change the visuals for your aesthetic necesities.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : Post pictures on social media with hashtag CalBot and we will feature you in our social media.
    fontawesome_icon_name                 : star

  - title                                 : Downloading/Unistalling
    description                           : You can download CalBot on the Apple Store or on the Play Store.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Social Media
    description                           : Follow us on social media and find out about updates, giveaways and more.
    fontawesome_icon_name                 : link

  - title                                 : Support
    description                           : Need technical support? Ask us anything at our forum.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.5

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown